Feature branch
Elisha-Tetteyfio/My-portfolio pull request #2
Opened 2022-04-22 20:31 UTC by Elisha-Tetteyfio

2022-04-22 23:13 UTC, mmsesay requested changes
Hi @Elisha-Tetteyfio, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 23:13 UTC, mmsesay commented on index.html
> +        <h2 class="menu-element" id="name">Elisha</h2>
- [ ] In best practices, site logos are a good place to easily set a redirection to the homepage or root of the site. In that case, please set this `h2` to an `a` tag.

2022-04-22 23:13 UTC, mmsesay commented on index.html
> +        <img src="Icons/Union.svg" alt="Menu" class="menu-element" id="menu">
- [ ] This is a hamburger menu. In that case, for semantic reasons, it will be nice to wrap the `img` tag inside a `nav` tag

2022-04-22 23:13 UTC, mmsesay commented on index.html
> +    </section>
- [ ] Please remove the border around the page contents. It is good to always follow the guidelines from the given design.

Your Design | Figma Design |
:---------------:|:------------------:|
![a1](https://user-images.githubusercontent.com/39523312/164815635-2c1ca007-9291-4de1-a4a6-d0b396dd8884.png)| ![a2](https://user-images.githubusercontent.com/39523312/164815641-b862862d-4eb8-4f01-8171-bb2b7d552397.png)

2022-04-22 23:13 UTC, mmsesay commented on index.html
> +    </section>
- [ ] Please remove the bullet points from lists. Just like I mentioned above, it will be nice to follow the given design.

Your Design | Figma Design |
:---------------:|:--------------------:|
![a1](https://user-images.githubusercontent.com/39523312/164816089-8edadb7c-15ec-44b9-903c-f90f7ace8393.png)| ![a2](https://user-images.githubusercontent.com/39523312/164816092-77314eb2-072b-4035-b4a7-e0518647b9f8.png)

2022-04-22 23:46 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi Elisha, 
## Congratulations 🎉 Thank you for implementing all the requirements 🙏
### Please go ahead and merge the branch!
# OPTIONAL
- [ ] Please see inline comments.
## Happy Coding 👏👏👏
#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-22 23:46 UTC, SajjadAhmad14 commented on index.html
> +        <a href="https://github.com/Elisha-Tetteyfio/Portfolio-setup-mobile-version-skeleton" class="menu-element" id="name">Elisha</a>
[ OPTIONAL ] Please remove the underline style from the logo.

2022-04-23 00:05 UTC, Elisha-Tetteyfio commented on index.html
> +        <a href="https://github.com/Elisha-Tetteyfio/Portfolio-setup-mobile-version-skeleton" class="menu-element" id="name">Elisha</a>
Sure

2022-04-23 00:23 UTC, merged